[application]

# App (Project) Name
name = "website"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "/Users/urthor/projects/website/public"

[web.app]

# HTML title tag content
title = "Hamish Poole"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["public/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[features]
default = ["web"]
web = ["dioxus-web", "dioxus-router/web"]
