# fly.toml app configuration file generated for hp-website-102 on 2023-05-08T18:01:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hp-website-102"
primary_region = "syd"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
