# fly.toml app configuration file generated for hp-website-101 on 2023-05-07T20:19:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hp-website-101"
primary_region = "syd"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
